mybatis:
  mapperLocations: classpath:mapper/**/*.xml #注意：一定要对应mapper映射xml文件的所在路径
  typeAliasesPackage: com.wjc.assess.entity   # 注意：对应实体类的路径

#spring.datasource.url = jdbc:mysql://localhost:3306/test?serverTimezone=UTC
#spring.datasource.username=root
#spring.datasource.password=1
#spring.datasource.driverClassName = com.mysql.cj.jdbc.Driver
# 这4个参数key里不带druid也可以，即可以还用上面的这个4个参数
spring:
  datasource:
    name: test
    url: jdbc:mysql://localhost:3306/mytest?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=GMT%2B8
    username: root
    password: 1
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    # 初始化时建立物理连接的个数
    initial-size: 5
    # 最大连接池数量
    max-active: 20
    # 最小连接池数量
    min-idle: 5
    # 获取连接时最大等待时间，单位毫秒
    max-wait: 5000
    # 配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
    time-between-eviction-runs-millis: 10000
    # 连接保持空闲而不被驱逐的最小时间
    min-evictable-idle-time-millis: 600000
    # 用来检测连接是否有效的sql，要求是一个查询语句
    validation-query: SELECT 1 FROM DUAL
    # 建议配置为true，不影响性能，并且保证安全性。申请连接的时候检测，如果空闲时间大于timeBetweenEvictionRunsMillis，执行validationQuery检测连接是否有效。
    test-while-idle: true
    # 申请连接时执行validationQuery检测连接是否有效，做了这个配置会降低性能。
    test-on-borrow: false
    # 归还连接时执行validationQuery检测连接是否有效，做了这个配置会降低性能。
    test-on-return: false
    # 是否缓存preparedStatement，也就是PSCache。PSCache对支持游标的数据库性能提升巨大，比如说oracle。在mysql下建议关闭。
    pool-prepared-statements: false
    # 要启用PSCache，必须配置大于0，当大于0时，poolPreparedStatements自动触发修改为true。
    max-pool-prepared-statement-per-connection-size: 50
    # 配置监控统计拦截的filters，去掉后监控界面sql无法统计
    filters: stat,wall
    # 通过connectProperties属性来打开mergeSql功能；慢SQL记录
    connection-properties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=500
    # 合并多个DruidDataSource的监控数据
    use-global-data-source-stat: true

  #返回的数据，时间戳统一转换
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8

#redis
#Matser的ip地址
  redis:
    #服务器地址
    host: 192.168.80.3
    #端口号
    port: 6379
    #Redis服务器连接密码（默认为空）
    password:
    #数据库索引
    database: 0
    #连接池最大连接数（使用负值表示没有限制）
    jedis:
      pool:
        max-active: 100
        # 连接池最大阻塞等待时间（使用负值表示没有限制）
        max-wait: -1
        # 连接池中的最大空闲连接
        max-idle: 20
        # 连接池中的最小空闲连接
        min-idle: 3
    # 连接超时时间（毫秒）
    timeout: 10000

# 打印sql
logging:
  level:
    com.wjc.assess.dao : debug
